<?php
/**
 * Created by PhpStorm.
 * User: jet
 * Date: 7/11/2016
 * Time: 5:25 PM
 */

namespace AlbumTest\Controller;

use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;

class AlbumControllerTest extends AbstractHttpControllerTestCase
{
    // To get a bit more information when something goes wrong in a test case, we set the protected $traceError member to true
    protected $traceError = true;

    public function setUp()
    {
        $this->setApplicationConfig(include rtrim(getcwd(), '/\\') . '/config/application.config.php');
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIndexActionCanBeAccessed()
    {
        $albumTableMock = $this->getMockBuilder('Album\Model\AlbumTable')
            ->disableOriginalConstructor()
            ->getMock();

//        $albumTableMock->expects($this->once())
//            ->method('fetchAll')
//            ->will($this->returnValue(array()));

        $serviceManager = $this->getApplicationServiceLocator();
        $serviceManager->setAllowOverride(true);
        $serviceManager->setService('Album\Model\AlbumTable', $albumTableMock);

        $this->dispatch('/album/add');
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('Album');
        $this->assertControllerName('Album\Controller\Album');
        $this->assertControllerClass('AlbumController');
        $this->assertMatchedRouteName('album');
    }
}