<?php
/**
 * Created by PhpStorm.
 * User: jet
 * Date: 7/13/2016
 * Time: 11:41 AM
 */
namespace Test\Controller;

use Zend\Mvc\Controller\AbstractActionController;

class IndexController extends AbstractActionController {

    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
}