<?php
/**
 * Created by PhpStorm.
 * User: jet
 * Date: 7/13/2016
 * Time: 11:41 AM
 */
namespace Test\Controller;

use Zend\Console\Prompt\Char;
use Zend\Console\Prompt\Confirm;
use Zend\Console\Prompt\Line;
use Zend\Console\Prompt\Password;
use Zend\Console\Prompt\Select;
use Zend\Di\Display\Console;
use Zend\Math\Rand;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\Console\Request as ConsoleRequest;
use Zend\View\Renderer\ConsoleRenderer;

class IndexController extends AbstractActionController
{

    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }


    // zf user resetpassword user@email.com
    // zf user resetpassword user@email.com --verbose
    // zf user resetpassword user@email.com -v
    public function resetpasswordAction()
    {
        $request = $this->getRequest();

//        var_export($request->getParam('userEmail'));
//        var_export($request->getParam('verbose'));
//        var_export($request->getContent());exit;


        // Make sure that we are running in a console and the user has not tricked our
        // application into running this action from a public web server.
        if (!$request instanceof ConsoleRequest) {
            throw new \RuntimeException('You can only use this action from a console!');
        }

        // Get user email from console and check if the user used --verbose or -v flag
        $userEmail = $request->getParam('userEmail');
        $verbose = $request->getParam('verbose') || $request->getParam('v');

        // reset new password
        $newPassword = Rand::getString(16);

        //  Fetch the user and change his password, then email him ...
        // [...]

        if (!$verbose) {
            return "Done! $userEmail has received an email with his new password.\n";
        } else {
            return "Done! New password for user $userEmail is '$newPassword'. It has also been emailed to him. \n";
        }
    }

    // 参数是按数序赋值的
    public function promptAction()
    {
        $request = $this->getRequest();

//        echo '<pre>';
//        var_export($request->getParam('userEmail'));
//        var_export($request->getParam('verbose'));
//        var_export($request->getParam('name'));
//        var_export($request->getContent());exit;

        if (!$request instanceof ConsoleRequest) {
            throw new \RuntimeException('You can only use this action from a console!');
        }

//         输入y 或 n
//        $confirm = new Confirm('Confirm:Are you sure you want to continue?');
//        $result = $confirm->show();
//        if ($result) {
//            echo "next step!\n";
//        } else {
//            echo "exit\n";
//            exit;
//        }

//        $prompt = Confirm::prompt('prompt:Are you sure you want to continue?');
//        echo $prompt . "\n";

//        if ( Confirm::prompt('Is this the correct answer? [y/n]', 'y', 'n') ) {
//            echo "You chose YES\n";
//        } else {
//            echo "You chose NO\n";
//        }

//        $name = Line::prompt("what's your name ?", false, 100);
//        echo "Good day to you $name!\n";

//        $answer = Char::prompt('What is the correct answer? [a,b,c,d,e]', 'abcde', true, false, true);
//        if ($answer == 'b') {
//            echo ('Correct. This it the right answer');
//        } else {
//            echo ('Wrong ! you lose.');
//        }

//        $options = array(
//            'a' => 'Apples',
//            'o' => 'Oranges',
//            'p' => 'Pears',
//            'b' => 'Bananas',
//            'n' => 'none of the above...'
//        );
//        $answer = Select::prompt('Which fruit do you like the best?', $options, false, false);
//        echo "You told me that you like " . $options[$answer];

//        $password = Password::prompt('Enter the secret', true);
//        echo "Sh!, the password is $password";

    }
}