<?php
/**
 * Created by PhpStorm.
 * User: jet
 * Date: 16-7-13
 * Time: 上午12:15
 */

namespace BlogPlatform\Controller;

use Zend\Mvc\Controller\AbstractActionController;

class IndexController extends AbstractActionController {

    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
}